# Generated by Django 5.1.7 on 2025-04-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': 'Тайтл', 'verbose_name_plural': 'Тайтлы'},
        ),
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.TextField(default='Нет описания', max_length=100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='title',
            name='title',
            field=models.CharField(max_length=25, verbose_name='Название тайтла'),
        ),
    ]
