# Generated by Django 5.1.7 on 2025-04-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler', '0002_alter_title_options_title_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleSecondPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_second', models.CharField(max_length=25, verbose_name='Название тайтла')),
                ('description_second', models.TextField(default='Нет описания', max_length=100, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тайтл',
                'verbose_name_plural': 'Тайтлы',
            },
        ),
    ]
