# Generated by Django 5.1.7 on 2025-04-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler', '0003_titlesecondpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstFromSecondPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_title', models.CharField(max_length=100, verbose_name='Название тайтла')),
                ('first_description', models.TextField(default='Нет описания', max_length=300, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тайтл-2_Первый Абзац',
            },
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': 'Тайтл'},
        ),
        migrations.AlterModelOptions(
            name='titlesecondpage',
            options={'verbose_name': 'Тайтл-2'},
        ),
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(default='Нет описания', max_length=300, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='title',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название тайтла'),
        ),
        migrations.AlterField(
            model_name='titlesecondpage',
            name='description_second',
            field=models.TextField(default='Нет описания', max_length=300, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='titlesecondpage',
            name='title_second',
            field=models.CharField(max_length=100, verbose_name='Название тайтла'),
        ),
    ]
