# Generated by Django 5.1.7 on 2025-04-01 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boiler', '0004_firstfromsecondpage_alter_title_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firstfromsecondpage',
            options={'verbose_name': 'Тайтл-2_Первый Абзац', 'verbose_name_plural': 'Тайтл-2_Первый Абзац'},
        ),
    ]
