# Generated by Django 5.1.7 on 2025-04-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler', '0006_secondfromsecondpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FourthFromSecondPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fourth_title', models.CharField(max_length=100, verbose_name='Название тайтла')),
                ('fourth_description', models.TextField(default='Нет описания', max_length=300, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тайтл-2_Четвертый Абзац',
                'verbose_name_plural': 'Тайтл-2_Четвертый Абзац',
            },
        ),
        migrations.CreateModel(
            name='ThirdFromSecondPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('third_title', models.CharField(max_length=100, verbose_name='Название тайтла')),
                ('third_description', models.TextField(default='Нет описания', max_length=300, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тайтл-2_Третий Абзац',
                'verbose_name_plural': 'Тайтл-2_Третий Абзац',
            },
        ),
    ]
