# Generated by Django 5.1.7 on 2025-04-01 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boiler', '0007_fourthfromsecondpage_thirdfromsecondpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firstfromsecondpage',
            options={'verbose_name': 'Тайтл-2_Первый Абзац', 'verbose_name_plural': 'Тайтлы-2_Первые Абзацы'},
        ),
        migrations.AlterModelOptions(
            name='fourthfromsecondpage',
            options={'verbose_name': 'Тайтл-2_Четвертый Абзац', 'verbose_name_plural': 'Тайтлы-2_Четвертые Абзацы'},
        ),
        migrations.AlterModelOptions(
            name='secondfromsecondpage',
            options={'verbose_name': 'Тайтл-2_Второй Абзац', 'verbose_name_plural': 'Тайтлы-2_Вторые Абзацы'},
        ),
        migrations.AlterModelOptions(
            name='thirdfromsecondpage',
            options={'verbose_name': 'Тайтл-2_Третий Абзац', 'verbose_name_plural': 'Тайтлы-2_Третьи Абзацы'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': 'Тайтл', 'verbose_name_plural': 'Тайтлы'},
        ),
        migrations.AlterModelOptions(
            name='titlesecondpage',
            options={'verbose_name': 'Тайтл-2', 'verbose_name_plural': 'Тайтлы-2'},
        ),
    ]
