# Generated by Django 5.1.7 on 2025-04-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler', '0008_alter_firstfromsecondpage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('availability', models.BooleanField(verbose_name='Наличие')),
                ('group', models.CharField(choices=[('1 вид', '1 вид'), ('2 вид', '2 вид'), ('3 вид', '3 вид'), ('4 вид', '4 вид')], default='1 вид', max_length=50, verbose_name='Категория')),
                ('img', models.ImageField(default='no_image.png', upload_to='img/', verbose_name='Изображение')),
            ],
        ),
    ]
