# Generated by Django 5.1.7 on 2025-04-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler', '0010_titlethirdpage_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=255, verbose_name='Заголовок 1 (h2)')),
                ('description1', models.TextField(verbose_name='Описание 1 (p)')),
                ('title2', models.CharField(max_length=255, verbose_name='Заголовок 2 (h3)')),
                ('description2', models.TextField(verbose_name='Описание 2 (p)')),
                ('title3', models.CharField(max_length=255, verbose_name='Заголовок 3 (h3)')),
                ('description3', models.TextField(verbose_name='Описание 3 (p)')),
                ('title4', models.CharField(max_length=255, verbose_name='Заголовок 4 (h3)')),
                ('description4', models.TextField(verbose_name='Описание 4 (p)')),
            ],
        ),
        migrations.DeleteModel(
            name='TitleThirdPage',
        ),
    ]
