# Generated by Django 5.1.7 on 2025-04-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler', '0011_feature_delete_titlethirdpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_title', models.CharField(max_length=100, verbose_name='Название тайтла 1')),
                ('first_description', models.TextField(default='Нет описания', max_length=300, verbose_name='Описание 1')),
                ('second_title', models.CharField(max_length=100, verbose_name='Название тайтла 2')),
                ('second_description', models.TextField(default='Нет описания', max_length=300, verbose_name='Описание 2')),
                ('third_title', models.CharField(max_length=100, verbose_name='Название тайтла 3')),
                ('third_description', models.TextField(default='Нет описания', max_length=300, verbose_name='Описание 3')),
                ('fourth_title', models.CharField(max_length=100, verbose_name='Название тайтла 4')),
                ('fourth_description', models.TextField(default='Нет описания', max_length=300, verbose_name='Описание 4')),
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Секции',
            },
        ),
        migrations.DeleteModel(
            name='FirstFromSecondPage',
        ),
        migrations.DeleteModel(
            name='FourthFromSecondPage',
        ),
        migrations.DeleteModel(
            name='SecondFromSecondPage',
        ),
        migrations.DeleteModel(
            name='ThirdFromSecondPage',
        ),
    ]
