# Generated by Django 4.2.20 on 2025-04-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler', '0015_secondimagemodel_alter_imagemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondimagemodel',
            name='second_image',
            field=models.ImageField(upload_to='backgrounds/', verbose_name='Изображение'),
        ),
    ]
