# Generated by Django 5.1.7 on 2025-04-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler', '0016_alter_secondimagemodel_second_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='client_logos/')),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
