# Generated by Django 5.1.7 on 2025-04-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler', '0017_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=20, verbose_name='Контакты')),
                ('hour', models.CharField(max_length=50, verbose_name='Время работы')),
                ('email', models.EmailField(max_length=255, verbose_name='EMAIL')),
            ],
        ),
    ]
