# Generated by Django 4.2.20 on 2025-04-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler', '0019_contactform_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedTelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100, unique=True, verbose_name='Telegram Chat ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Пользователь Telegram',
                'verbose_name_plural': 'Пользователи Telegram',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
