# Generated by Django 5.1.7 on 2025-04-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler', '0019_contactform_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teammate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teammate_image', models.ImageField(upload_to='media/')),
                ('teammate_name', models.CharField(max_length=255)),
                ('teammate_description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Член команды',
                'verbose_name_plural': 'Член команды',
            },
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Наш клиент', 'verbose_name_plural': 'Наши клиенты'},
        ),
        migrations.AlterModelOptions(
            name='contactform',
            options={'verbose_name': 'Контактная форма', 'verbose_name_plural': 'Контактные формы'},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'Наша услуга 2-я страница', 'verbose_name_plural': 'Наши услуги 2-я страница'},
        ),
        migrations.AlterModelOptions(
            name='pagebackground',
            options={'verbose_name': 'Изображение для главной страницы сайта', 'verbose_name_plural': 'Изображения для главной страницы сайта'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Наш Котел', 'verbose_name_plural': 'Наши Котлы'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Наша услуга главная страница', 'verbose_name_plural': 'Наши услуги главная страница'},
        ),
        migrations.AlterModelOptions(
            name='titlesecondpage',
            options={'verbose_name': 'Наша услуга', 'verbose_name_plural': 'Наши услуги'},
        ),
    ]
