# Generated by Django 4.2.20 on 2025-04-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler', '0020_allowedtelegramuser_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowedtelegramuser',
            name='chat_id',
        ),
        migrations.RemoveField(
            model_name='allowedtelegramuser',
            name='name',
        ),
        migrations.AddField(
            model_name='allowedtelegramuser',
            name='username',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Telegram Username'),
            preserve_default=False,
        ),
    ]
