# Generated by Django 5.1.7 on 2025-04-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler', '0020_teammate_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammate',
            options={'verbose_name': 'Член команды', 'verbose_name_plural': 'Члены команды'},
        ),
        migrations.AddField(
            model_name='teammate',
            name='teammate_position',
            field=models.CharField(default='', max_length=255),
        ),
    ]
