# Generated by Django 4.2.20 on 2025-04-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler', '0022_telegramuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllowedTelegramUser',
        ),
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'telegram_user', 'verbose_name_plural': 'telegram_users'},
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='chat_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='telegramuser',
            table='telegram_users',
        ),
    ]
