# Generated by Django 5.1.7 on 2025-04-16 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boiler', '0021_alter_teammate_options_teammate_teammate_position'),
        ('boiler', '0023_delete_allowedtelegramuser_and_more'),
    ]

    operations = [
    ]
