# Generated by Django 5.1.7 on 2025-04-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler', '0024_merge_20250416_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='unified_images/', verbose_name='Изображение')),
                ('image_type', models.CharField(choices=[('main_bg', 'Фон главной страницы'), ('upload', 'Просто изображение'), ('second_bg', 'Фон следующей страницы')], max_length=20, verbose_name='Тип изображения')),
            ],
            options={
                'verbose_name': 'Объединённое изображение',
                'verbose_name_plural': 'Объединённые изображения',
            },
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
        migrations.DeleteModel(
            name='PageBackground',
        ),
        migrations.DeleteModel(
            name='SecondImageModel',
        ),
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'телеграм_бот', 'verbose_name_plural': 'телеграм_боты'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': 'Описание главной страницы', 'verbose_name_plural': 'Описания главной страницы'},
        ),
    ]
