# Generated by Django 5.1.7 on 2025-04-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler', '0025_unifiedimage_delete_imagemodel_delete_pagebackground_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('твердотопливные', 'твердотопливные'), ('газовые', 'газовые'), ('электрические', 'электрические'), ('комбинированные', 'комбинированные')], default='твердотопливные', max_length=50, verbose_name='Категория'),
        ),
    ]
