# Generated by Django 5.2 on 2025-04-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler', '0026_alter_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifiedimage',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='Изображение'),
        ),
    ]
