# Generated by Django 5.2 on 2025-05-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler', '0027_alter_unifiedimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('твердотопливные', 'твердотопливные'), ('банный', 'банный'), ('парогенератор', 'парогенератор'), ('расширительный бак', 'расширительный бак'), ('дымоход', 'дымоход')], default='твердотопливные', max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='unifiedimage',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
    ]
